apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: default
  labels:
    app: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
