apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-api-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask-api
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
