version: "3.9"

services:
  db:
    image: postgres:16
    container_name: devops_starter_db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - devnet

volumes:
  db_data:
