global:
  scrape_interval: 15s

scrape_configs:
  - job_name: flask
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]   # داخل شبکه devnet با نام سرویس
  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: ["loki:3100"]
  - job_name: promtail
    metrics_path: /metrics
    static_configs:
      - targets: ["promtail:9080"]