name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: false

      - name: Push Docker image
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-gitops:latest

      - name: Update Kubernetes manifest
        run: |
          sed -i "s#image: .*#image: ${{ secrets.DOCKERHUB_USERNAME }}/flask-gitops:latest#g" monitoring/grafana/provisioning/monitoring/monitoring/manifests/deployment.yaml
      - name: Commit and push updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add monitoring/grafana/provisioning/monitoring/monitoring/manifests/deployment.yaml
          git commit -m "Update image to latest [skip ci]" || echo "No changes to commit"
          git push